services:
  apisix:
    image: apache/apisix:3.9.0-debian
    volumes:
      - ./apisix/config/static/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - bundles-data:/var/bundles:ro
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.5.13
    environment:
      ETCD_ENABLE_V2: true
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2397
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2397
  opa:
    image: openpolicyagent/opa:0.63.0
    command:
      - "run"
      - "--server"
      - "-c"
      - "/var/opa/config.yml"
    volumes:
      - ./opa/config.yml:/var/opa/config.yml:ro
    depends_on:
      - apisix
  bundler:
    image: openpolicyagent/opa:0.63.0
    working_dir: /var/bundles
    user: root
    command:
      - "build"
      - "/var/policy"
    volumes:
      - ./policy:/var/policy:ro
      - bundles-data:/var/bundles:rw
  boot:
    image: secure-boot:1.1
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=secure
      APP_OPA_ENDPOINT: http://opa:8181/v1/data/ch/frankel/blog/secureboot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
volumes:
  bundles-data: